### PR TITLE
bump: version 0.3.3

### PR DESCRIPTION
**Pull request by guybedford**

### CODE REVIEW

**Review by cfallin — APPROVED** [review]
Ship it!

**Comment by guybedford** [comment]
I've published to npm, unfortunately I don't have permissions to publish the crate though.

**Comment by cfallin** [comment]
Ah, I've added `github:bytecodealliance:wasmtime-publish` to the crate permissions, could you see if it works now?

**Comment by guybedford** [comment]
Unfortunately still not.

**Comment by cfallin** [comment]
OK, I added `guybedford` directly to the crate ACL, hopefully that'll work!

**Comment by guybedford** [comment]
Interestingly, still not!

**Comment by guybedford** [comment]
Ahh I had to accept the invite on my personal email account. Just got it published.

**Pull request merged**
